### ISSUE TITLE
How to add The-Java-Workshop directory to IntelliJ

### ISSUE THREAD

**Issue by Gritsn** [TrainingByPackt/The-Java-Workshop#3]
I have tried to create a new project and select "The-Java-Workshop directory" after I finish I can find the directory folders and subfolders, but once I try to load a file and run it I get several errors "Error:(1, 8) java: duplicate class: Main"

![galil-0002](https://user-images.githubusercontent.com/67023167/85215058-6e380f00-b373-11ea-9032-b10abcdc497e.png)

I am a beginner and would appreciate any help on that regard,
Thanks,
Rami

**Comment by agoransson** [comment]
Hello @RGitabs, thank you for downloading the project. It sounds as though you're running the entire project - which does have many "main files". Try adding a single Activity or Exercise as a project in your Java IDEA and run that.

**Comment by Gritsn** [comment]
Thanks a lot @agoransson for your quick reply. When I first posted this question I did not reach the part in the book where you explain how to create a new project for study activities and then add classes for each exercise, I am now at exercise 16 and can't be any happier! Nice work!

**Comment by agoransson** [comment]
Good job @RGitabs! Glad you solved it on your own. I will close this now.
